name: scoped_zone
description: A lightweight and intuitive dependency injection library for Dart applications leveraging Zones.
version: 0.2.0
homepage: https://github.com/rkishan516/scoped_zone
repository: https://github.com/rkishan516/scoped_zone

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.16.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.13
  very_good_analysis: ^7.0.0
